# Generated by Django 5.2.7 on 2025-10-22 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feadback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fead_dec', models.TextField()),
                ('fead_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doctors')),
            ],
        ),
    ]
